### ISSUE TITLE
ESWC Papers

### ISSUE THREAD

**Issue by lara-hdr** [anuzzolese/oke-challenge-2016#13]
Hello,
I would like to know if there is a presentation for the published papers.
Also, are the data test going to be given during the ESWC or beforehand?
Thank you

**Comment by AnLiGentile** [comment]
Dear Lara,
we added a provisional schedule at https://github.com/anuzzolese/oke-challenge-2016#oke-challenge-at-eswc2016 and also sent further information via easychair, with some action requests for the authors.
Thanks!
Annalisa
