### ISSUE TITLE
Submission Deadline

### ISSUE THREAD

**Issue by lara-hdr** [anuzzolese/oke-challenge-2016#8]
Hi,
I wanted to make sure if the first deadline (Monday March 21st 2016) is the submission deadline for both the paper and the web service, or only the paper.

Thank you

**Comment by AnLiGentile** [comment]
Dear Lara,
the 21st of March is the deadline for the paper submission.
The URI for the final system must be provided by April 8th, 2016.
Hope that helps.
Bests
Annalisa
